services:
  puppeteer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapping_container
    ports:
      - "3000:3000"
    restart: always
    # IMPORTANTE: Limpia procesos de Chrome colgados para evitar Timeouts
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"